### ISSUE TITLE
[QUESTION] Provide Install Numbers?

### ISSUE THREAD

**Issue by jyee999** [ailabstw/social-distancing#5]
Is there a place to see install numbers for the Apple and Google platforms?  Are you willing to provide these numbers?   A check on the Google Play Store install number seems to only show 8800+ installs (which seems low).

**Comment by githorray** [comment]
The count recently increased to 1M+ installs on android.

https://play.google.com/store/apps/details?id=tw.gov.cdc.exposurenotifications

**Comment by jyee999** [comment]
Thank for the clarifying.
