### ISSUE TITLE
Cannot init app on iOS (not test under Android)

### ISSUE THREAD

**Issue by mingtsay** [ailabstw/social-distancing#7]
# Description

App won't enable properly.
Same situation on both iPhone 6s and iPhone 12 mini with iOS 14.6 (the latest one)
Logs screen showed up the wrong init date.

# Reproduce Step

1. Install the app via App Store
2. Launch the app
3. Read the introduction of the app
4. Blank screen will shows up

# Screenshots:

![Blank Screen](https://user-images.githubusercontent.com/760655/123844358-83ac2580-d945-11eb-8364-d1b14b4e49e3.png)
![Logs](https://user-images.githubusercontent.com/760655/123844374-89097000-d945-11eb-9400-450ac545d900.png)
![Setting Screen 1](https://user-images.githubusercontent.com/760655/123844394-8e66ba80-d945-11eb-9361-a30d92a2d6f6.png)
![Setting Screen 2](https://user-images.githubusercontent.com/760655/123844407-9161ab00-d945-11eb-9e80-ef3a0583591a.png)

**Comment by ShivaHuang** [comment]
Version 1.4.0 solved this problem. Sorry for inconvenience.

**Comment by mingtsay** [comment]
Confirmed. Issue solved. Closing the issue.
